typechecker fixes
StarikTenger/Chipollino pull request #122
Opened 2022-11-10 23:47 UTC by mathhyyn

closes #88 
Ура! Наконец-то можно адекватно тестировать через интерпретатор (спустя 2 недели 😢)

2022-11-10 23:53 UTC, TonitaN commented
Я, конечно, одобряю прогресс, но по логике распределения задач тестировщик должен выдавать маты, а не правки, а правки - это дело тех, кто приписан к реализации фронтенда (и кого мы больше всего ждём).

2022-11-11 00:09 UTC, mathhyyn commented
> Я, конечно, одобряю прогресс, но по логике распределения задач тестировщик должен выдавать маты, а не правки, а правки - это дело тех, кто приписан к реализации фронтенда (и кого мы больше всего ждём).

делать нечего, раз появилось настроение заняться проектом, когда ответственные спят (террором не обделены)

2022-11-11 18:07 UTC, StarikTenger requested changes

2022-11-11 18:07 UTC, StarikTenger commented on src/Interpreter.cpp
> +			vector<ObjectType> d = {ObjectType::DFA};
только сейчас заметил, что переменные называются `r`, `d`, `n`...

уж лучше regex_input, nfa_input, dfa_input

2022-11-11 18:21 UTC, mathhyyn commented on src/Interpreter.cpp
> +		return false;
проблема...

2022-11-15 12:17 UTC, StarikTenger approved these changes

2022-11-15 12:18 UTC, merged