Фикс моноида
StarikTenger/Chipollino pull request #125
Opened 2022-11-11 10:59 UTC by xtoter

Убрал старых багов, завез новых. Вроде живое и все хорошо)
Исправлена проверка на принадлежность языку, поправлена ошибка с удалением ловушек и убрал фикспоинт

2022-11-11 11:00 UTC, xtoter commented
Ждем https://github.com/StarikTenger/Chipollino/pull/115

2022-11-11 17:38 UTC, StarikTenger requested changes
раз уж делается фикс, хорошо бы и кодстайл поправить:
* не надо называть переменные с заглавной буквы, это относится в том числе к _`get_Equalence_Classes`_,`_get_Equalence_Classes_VW_`, `_get_Equalence_Classes_WV_`, `_get_Equalence_Classes_VWV_`, `_get_Rewriting_Rules_`, Ну и другие методы
* *`Transition`*, *`Term`*, *`TermDouble`*, *`class_card_typecheker`*, *`class_legth_typecheker`*, *`MyhillNerode_typecheker`* стоит внести внутрь класса
* публичные методы стоит подписать комментариями

2022-11-11 17:38 UTC, StarikTenger commented on include/objects/TransformationMonoid.h
> +	TransformationMonoid(FiniteAutomaton* in); //Автомат и макс длина перехода
лучше через константную ссылку
```c++
TransformationMonoid(const FiniteAutomaton& in)
```

2022-11-11 17:38 UTC, StarikTenger commented on src/objects/TransformationMonoid.cpp
> +	TransformationMonoid a(in);
*class_card_typecheker*, *MyhillNerode_typecheker*, *class_legth_typecheker* лучше внести как статические методы в моноид. Ну и пусть принимают `const FiniteAutomaton&`

так же стоит написать, что они делают в *.h*-файле

2022-11-11 18:13 UTC, TonitaN commented
Плюсую за рефакторинг. Если в коде @shevchenkokk и @Robby-the-paladin я без проблем могу что-то для себя поменять, и всё самодокументировано, то попытка видоизменить Arden для тестирования вылилась в то, что пришлось печатать все промежуточные результаты всяких `temp.temp`-ов, чтобы разобраться, что происходит, и всё-таки разобралась не полностью. В моноиде я тоже вижу `temp`-ы и `cond`-ы, и если смотреть с точки зрения продления жизни проекта, это не есть добро.

2022-11-12 00:05 UTC, TonitaN commented
Переименовать `cond`-ы и `cond1`-ы всё-таки нужно по-человечески.  И `sost` и особенно `endsost` --- это ж0сткая обфускация кода для англоязычных пользователей, которые ожидали бы увидеть `state`. В моноиде к `temp`-ам придираться особенно не буду - они в принципе по делу (хотя почему-то иногда используется `temp1`, для тех же целей, и лучше было бы называть их `new_transition`), но в ардене буду требовать `temp`-ы расшифровать.

2022-11-12 20:17 UTC, xendalm commented on include/objects/TransformationMonoid.h
> +	bool is_minimality(); //Вычисление Минимальности (1 если минимальный)
Минимальности чего? Если нам это не надо знать, то в private :)) 
(is_minimal)

2022-11-12 22:38 UTC, xendalm commented
А логи?( Эти функции ничего не логируют, а их будет вызывать интерпретатор 
int class_card(); 
int class_length(); 
int classes_number_MyhillNerode();

2022-11-14 19:30 UTC, xendalm approved these changes

2022-11-14 20:35 UTC, merged