Мера неоднозначности в среднем
StarikTenger/Chipollino pull request #177
Opened 2022-11-29 23:33 UTC by xendalm

Исправляю ошибки

2022-12-02 15:04 UTC, StarikTenger requested changes

2022-12-02 16:44 UTC, xendalm commented on libs/Objects/src/FiniteAutomaton.cpp
> +
К сожалению, время в текущей реализации зависит не только от этого параметра, а еще от глубины рекурсии и от того, сократима ли дробь (🙁). Я подумаю, как это лучше реализовать...

2022-12-02 18:47 UTC, TonitaN commented
Физический таймер либо надо вынести вовне (т.е. сделать таймаут одинаковым и контролируемым для всех интерпретируемых функций) и завернуть все функции в эту оболочку, либо уж попробовать заменить абстрактным, чтобы не вмешивать побочные эффекты только в одну функцию. А лучше абстрактное ограничение всё равно сделать и не возиться пока что с побочными эффектами. Как строить оценочную функцию, я попыталась объяснить.

2022-12-12 12:50 UTC, xendalm commented
Метод все еще может работать долго, но по моим наблюдениям (тестах на генераторе) это происходит из-за функций минимизации и удаления эпсилон-переходов.

2022-12-23 14:43 UTC, StarikTenger approved these changes

2022-12-23 14:43 UTC, merged