Automaton to prefix grammar
StarikTenger/Chipollino pull request #188
Opened 2022-12-05 13:23 UTC by dak151449

2022-12-05 17:52 UTC, StarikTenger requested changes

2022-12-05 17:52 UTC, StarikTenger commented on apps/TestsApp/src/main.cpp
> +	Example::fa_to_pgrammar();
*main()* в TestsApp менять не надо, `fa_to_pgrammar` добавь в `Example::all_examples`

Так же надо сделать не только пример, но и тесты

2022-12-05 17:52 UTC, StarikTenger commented on libs/Objects/include/Objects/Grammar.h
> +		const FiniteAutomaton&); // создание пр грамматики по НКА с помощью ТМ
1. Почему `fa_to_prefix_grammar`, `fa_to_prefix_grammar_TM`, `prefix_grammar_to_automato` не **static**?

2. Комментарии лучше писать перед методом (посмотри, чтобы в остальных функциях так же было):
```c++
// создание пр грамматики по НКА
static vector<vector<GrammarItem>> fa_to_prefix_grammar(const FiniteAutomaton&); 
// создание пр грамматики по НКА с помощью ТМ
vector<vector<GrammarItem>> fa_to_prefix_grammar_TM(const FiniteAutomaton&); 
```

3. Для методов надо добавить тесты с использованием *assert*

2022-12-05 18:07 UTC, xendalm requested changes

2022-12-05 18:07 UTC, xendalm commented on libs/Objects/include/Objects/Grammar.h
> +	map<int, GrammarItem> prefix_grammar;
Я использовал класс Grammar только как интерфейс для работы с GrammarItem. @dak151449 уже напрямую использует экземпляры, поэтому видимо и появились не static методы. 

Только вот, наверное, не очень правильно называть это поле prefix_grammar, потому что грамматика может быть не только префиксной.

2022-12-05 18:07 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +						   int index_back, map<int, GrammarItem*> grammer_items,
grammar, а не grammer

Нужно везде изменить

2022-12-05 18:26 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +	map<int, GrammarItem> gr_it = prefix_grammar;
Почему в этом и других методах используется `gr_it`? Насколько я понимаю, to_txt() точно не должен менять поле класса, зачем тогда лишнее копирование.

2022-12-05 18:26 UTC, xendalm commented on libs/Objects/include/Objects/Grammar.h
> +	map<alphabet_symbol, set<int>> rules;
Нужно добавить комментарии к этим полям

2022-12-08 19:12 UTC, dak151449 commented on libs/Objects/include/Objects/Grammar.h
> +		const FiniteAutomaton&); // создание пр грамматики по НКА с помощью ТМ
fa_to_prefix_grammar, fa_to_prefix_grammar_TM меняют объект, поле prefix_grammar

2022-12-16 18:04 UTC, xendalm requested changes

2022-12-16 18:04 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +							  map<int, bool> is_visit) {
Может ли быть не map?

2022-12-16 18:04 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +							  set<string> monoid_rules, string word,
Это надо передавать по ссылке.

2022-12-16 18:06 UTC, xendalm requested changes

2022-12-16 18:06 UTC, xendalm commented on libs/Objects/include/Objects/Grammar.h
> +		map<int, bool>); //вспомогательная функции для
Насколько я понимаю, эти vector и set можно передавать по ссылке

2022-12-16 18:14 UTC, xendalm commented on libs/Objects/include/Objects/Grammar.h
> +								  // потом, возможно, можно будет убрать
Этот метод должен быть статическим. Лучше перенести в структуру alphabet_symbol (vector_to_str например). Заодно из моноида эту функцию тоже убрать

2022-12-16 18:23 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +	vector<State> states = fa.states;
`const vector<State>& states`
Все аналогичные копирования полей автомата надо переделать в константные ссылки

Это касается и отдельных экземпляров State, которые берутся из fa.states

2022-12-16 18:23 UTC, xendalm commented on libs/Objects/src/Grammar.cpp
> +	vector<State> states_fa = fa.states;
В чем отличие между states и fa_states?

2022-12-17 22:23 UTC, xendalm approved these changes

2022-12-21 00:26 UTC, TonitaN commented
+3, спасибо!

2022-12-23 15:27 UTC, StarikTenger approved these changes

2022-12-23 15:27 UTC, merged