Демоверсия интерпретатора с расширенным функционалом
StarikTenger/Chipollino pull request #202
Opened 2022-12-23 22:17 UTC by mathhyyn

2022-12-24 20:04 UTC, StarikTenger requested changes

2022-12-24 20:04 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +	bool is_trim = true;
надо подписать, что значит флаг: что значат включенное и выключенное состояния

2022-12-24 22:08 UTC, StarikTenger requested changes
флаг *is_trim* в интерпретаторе (см. коммент выше). Может, вообще его пока убрать

2022-12-24 22:33 UTC, xendalm commented
Получается методы будут менять только флаг самого автомата, а интерпретатор будет рассматривать результат как новый тип?

2022-12-24 22:36 UTC, mathhyyn commented
> Получается методы будут менять только флаг самого автомата, а интерпретатор будет рассматривать результат как новый тип?

Нет, мы решили добавить операцию setFlag, реализация которой ненадолго откладывается

2022-12-24 22:54 UTC, xendalm commented
А флаг в автомате нужен только для режима, когда флаг включен, чтобы методы знали, когда обрабатывать автоматы с ловушками?

2022-12-24 23:17 UTC, mathhyyn commented
> А флаг в автомате нужен только для режима, когда флаг is_trim интерпретатора включен, чтобы методы знали, когда обрабатывать автоматы с ловушками?

Теперь, перечитав issue, мне кажется, что флаг должен не пользователь устанавливать, а тайпчекер, отслеживая переходы nfa->dfa и dfa->dfa. И вообще надо добавить функцию RemoveTrap. Буду уточнять...

2022-12-24 23:24 UTC, TonitaN commented
Сегодня как раз об этом вроде бы говорили с @xendalm : по умолчанию считаем всё trim, а если уж ловушка точно нужна для демонстрации (например, дополнения), она показывается и остаётся до тех пор, пока станет не нужна, либо вызовется функция, приводящая к trim-форме (например, минимизация). И явные функции управления ловушкой (добавления и удаления) тоже нужны в интерпретаторе.
Кстати, если с равенством и с эквивалентностью и ловушками всё понятно (эквивалентность они не рушат, а равенство рушат), то бисимуляция, по-видимому, тоже зависит от наличия или отсуствия ловушки. Т.е. два равных автомата, с ловушкой и без, не будут бисимилярны, и это кажется логичным, т.к. в определении бисимуляции важны только переходы в lts, а не их продуктивность.

2022-12-26 21:41 UTC, StarikTenger requested changes

2022-12-26 21:41 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Typization.h
> +using ObjectPG = ObjectHolder<ObjectType::PrefixGramnar, Grammar>;
Раз уж в enum ObjectValue, OptionalBool и PrefixGramnar то и тут надо переименовать

*(сам сделаю)*

2022-12-26 21:45 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Typization.h
> +	PrefixGramnar				// префиксная грамматика
gram**n**ar -> grammar

2022-12-26 21:55 UTC, StarikTenger approved these changes

2022-12-26 21:55 UTC, merged