Interpreter changes only
StarikTenger/Chipollino pull request #221
Opened 2023-01-06 15:05 UTC by mathhyyn

для проверки
(почти) новый тайпчекер
операция setFlag (поменяется потом на просто set)

2023-01-14 02:19 UTC, TonitaN commented
Качаю актуальную версию из ветки для сверки с ней (пока отсутствующего) шаблона.

2023-01-14 12:36 UTC, StarikTenger requested changes
Главное и основное - про рандомизацию регулярок. Но мелочи тоже стоит исправить

успехов!

2023-01-14 12:36 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +	bool set_flag(const Flag&);
`set_flag` лучше перенести в public (и тогда флаговый енум тоже)

2023-01-14 12:36 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Typization.h
> +	String,		 // имя файла для чтения
про *RandomRegex*:
Так как рандомизация регулярки параметризуется, то лучше её сделать функцией с параметрами (такой же функцией, как и все остальные)

`RandomRegex :: (Int, Int) -> Regex`

2023-01-17 20:13 UTC, TonitaN commented
Засчитываю 3 ЛР @mathhyyn , чуть-чуть авансом до слияния, т.к. всё равно требуемые изменения она точно внесёт. Но чтобы спокойнее было.

2023-01-17 20:30 UTC, mathhyyn commented
> Засчитываю 3 ЛР @mathhyyn , чуть-чуть авансом до слияния, т.к. всё равно требуемые изменения она точно внесёт. Но чтобы спокойнее было.

Ночью доделаю, завтра сольем (надеюсь)

2023-01-18 09:42 UTC, StarikTenger requested changes

2023-01-18 09:42 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +		verification
Вызывает большие сомнения флаг `verification`.

Всё-таки подразумевается, что флаги из `map flags` нужен для флагов, которые регулируются пользователем. *Verification*, в свою очередь, нужен исключительно для внутреннего пользования.

Странно, что используется он и в сканере и в раннере. Странно и то, что во время сканирования *true* присваивается внутри scan_verification, а возвращается в *false* он снаружи. 

Как по мне, лучше его и вовсе из сканера убрать, так как всё равно у терма-звёздочки других значений, кроме *RandomRegex* нет, следовательно контекст для сканирования данного терма не нужен (да, это запрещает ставить * в выражения, кроме, верификации, но это можно сделать и динамически).

### Предлагаемое решение
* убрать флаг verification
* пока что использовать для всего, связанного с рандомными регулярками *current_random_regex*
* сделать *current_random_regex* типа `optional<Regex>`, через `nullopt` обозначать отсутсвие текущего выражения
* *current_random_regex* не `nullopt` только в рамках выполнения верификации, в eval_expression сделать проверку на наличие выражения в случае звёздочки

В будущем, конечно, надо будет пересмотреть архитектуру и найти способ сделать красиво, но, пока и так сгодится

2023-01-18 09:42 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +		verification
кстати, current_random_regex имеет смысл перенести в раздел "исполнение команд", так как к выполнению он и имеет отношение

2023-01-18 09:42 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +		{"log_theory", Flag::theory},
раз переименовались строковые значения флагов, надо бы и поля енума переименовать

2023-01-18 09:42 UTC, StarikTenger commented on libs/Interpreter/include/Interpreter/Interpreter.h
> +	};
вместо текущего `set_flag` надо сделать `run_set_flag`, подобный остальным run-функциям (технически, `set_flag` таким и является, но название у него выбивается и лежит он сейчас в паблике)

просто надо сделать дополнительно в паблике `set_flag`, чтобы флаги можно было ставить по енуму из кода

2023-01-18 15:52 UTC, StarikTenger commented
берусь переделывать, посмотрим, правда ли это будет быстрее, чем ревьюить

2023-01-18 19:30 UTC, StarikTenger approved these changes

2023-01-18 19:31 UTC, merged