Чиполиноо 2.0
StarikTenger/Chipollino pull request #254
Opened 2023-01-27 00:47 UTC by mathhyyn

да.

2023-01-27 01:04 UTC, mathhyyn commented
рефал...
![image](https://user-images.githubusercontent.com/79749959/214984244-462104e3-822d-452f-b85b-e17be557d540.png)
он пытается...

2023-01-27 01:23 UTC, TonitaN commented
Так, а для модуля автотестов ведь рефал не должен подключаться? Не должен же?

2023-01-27 02:10 UTC, mathhyyn commented
> Так, а для модуля автотестов ведь рефал не должен подключаться? Не должен же?
> 
> Это принципиальный момент, что в TestsApp у нас сейчас вообще вызывается только тест рефала?
> 
> UPS: Предположим на минутку страшное: рефал в какой-нибудь нормализации и в автотестах. Ведь тогда точно ничего не соберётся...

Не должен...
Может что то и сломалось

2023-01-27 03:27 UTC, mathhyyn commented
ладно
![IMG_20230127_062952](https://user-images.githubusercontent.com/79749959/215003668-4c4762e1-90ce-43e3-aea6-c46ddbf0917c.jpg)

2023-01-27 03:28 UTC, xtoter commented
Щя точно последний будет, я вроде отдебажил

2023-01-27 22:01 UTC, StarikTenger requested changes

2023-04-09 16:05 UTC, xendalm commented on libs/Interpreter/src/Interpreter.cpp
> +	}
Вообще не уверен, что в ней есть смысл, потому что уровнями выше это вроде как проверяется. Но дописал как смог

2023-04-16 15:57 UTC, StarikTenger commented
Ну, погнали проверять. Будет сложно, я уже забыл добрую часть проекта

2023-04-16 16:12 UTC, StarikTenger commented on apps/InputGeneratorApp/src/main.cpp
> +	TG.generate_task(10, 10, false, false);
По-хорошему, надо сделать нормальный интерфейс генератору, чтобы, например, можно было из командой стоки его запускать как хочется.

Это на будущее, можно в issue выделит

2023-04-17 10:38 UTC, StarikTenger requested changes
В целом, всё хорошо. Сложно что-то сказать про бэкенд, я его хоть и посмотрел, но вполне мог что-то упустить, так что буду просто верить, что там всё работает

2023-04-17 10:38 UTC, StarikTenger commented on libs/Logger/include/Logger/LogTemplate.h
> +	string tex_template;
Я бы переименовал `tex_template` -> `template_fullpath`, а то название сбивает с толку

2023-04-17 10:38 UTC, StarikTenger commented on libs/Logger/include/Logger/LogTemplate.h
> +	static string math_mode(string str);
> `// math mode`

Очень информативный комментарий, я сразу всё понял 👍

Понятное дело, что мы все сейчас примерно представляем, что такое *math mode*, и что он делает, да и где-то там в issue это написано. Но лучше оставлять понятный комментарий, что функция делает, чтобы не приходилось лезть в реализацию, чтобы удостовериться, правильно ли я угадал смысл метода.

К примеру, для *math_mode* достаточно будет написать, что он преобразует строку в латеховский математический формат

2023-04-17 10:38 UTC, StarikTenger commented on libs/Logger/include/Logger/LogTemplate.h
> +	static string log_table(Table t);
см. предыдущий комментарий

2023-04-19 13:33 UTC, StarikTenger approved these changes

2023-04-19 13:34 UTC, merged