Бисимилярность и равенство автоматов
StarikTenger/Chipollino pull request #27
Opened 2022-10-14 16:16 UTC by xendalm

Добавлены функции:

- Проверка автоматов на равенство
- Проверка регулярок на равенство
- Проверка автоматов на бисимилярность
- Объединение эквивалентных по бисимуляции состояний автомата

2022-10-17 23:12 UTC, StarikTenger requested changes

2022-10-17 23:12 UTC, StarikTenger commented on src/objects/FiniteAutomat.cpp
> +		vector<vector<GrammarItem*>> tempRules;
temp_rules

2022-10-18 11:31 UTC, xtoter approved these changes

2022-10-18 12:10 UTC, StarikTenger approved these changes

2022-10-18 12:10 UTC, merged