Add pda
StarikTenger/Chipollino pull request #325
Opened 2024-02-19 21:19 UTC by alien-agent

Добавлен тип PDA. Поддержаны методы: 

- Determinize <PDA> -> <DPDA>
- Deterministic <PDA> -> <Boolean>
- RegularIntersect <PDA, Regex> -> <PDA>
- Complement <DPDA> -> <DPDA>
- Test <PDA, Integer> -> <Table>

По умолчанию на стэке лежит символ `Symbol::StackTop == "z0"`. Каждый переход должен снимать со стэка ровно один символ. Каждый переход может класть на стэк несколько символов (чтобы не класть ничего на стэк, нужно передать eps в качестве push символа).

2024-02-19 22:57 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +	hash += 123;
Пока не смотрел в целом код, но интересно, как это работает?

2024-02-20 06:45 UTC, alien-agent commented on libs/Objects/src/PushdownAutomaton.cpp
> +	hash += 123;
Хаха, уже забыл про этот момент)
На самом деле, несмотря на то что hash не работает, оператор сравнения реализован верно. При вставке очередного элемента в set/map при совпадении хешей объекты проверяются еще и на буквальное равенство. Ну и получается что все PDATransition складываются в один bucket хеш-таблицы - неэффективно, но работает)

2024-02-20 07:02 UTC, alien-agent commented on libs/Objects/src/PushdownAutomaton.cpp
> +	hash += 123;
Сегодня поправлю

2024-02-20 20:39 UTC, xendalm requested changes

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +std::vector<PDATransition> get_epsilon_transitions(const string& s,
s лишнее

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +	auto result = stack;
Если stack передается не по ссылке, то он уже скопирован в аргумент и можно не создавать вспомогательный result

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +	set<tuple<int, int, int>> visited_eps;
Должно характеризоваться не только этой тройкой, но еще и состоянием стека. Для MFA - состоянием памяти, внес этот фикс недавно.
Можно тоже переделать на unordered_set с хэшированием

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +	std::map<int, int> recover_index;
unordered )

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +	set<Symbol> result_alphabet;
Используй Alphabet из Symbol.h (и в 260 строке)

2024-02-20 20:39 UTC, xendalm commented on libs/Objects/include/Objects/PushdownAutomaton.h
> +	[[nodiscard]] std::set<Symbol> _get_stack_symbols() const;
Думаю, здесь можно сразу использовать unordered (для алфавита используется set по историческим причинам)

2024-02-20 20:41 UTC, xendalm commented on libs/AutomataParser/src/Parser.cpp
> +	// https://lexy.foonathan.net/playground/
Насколько я понял, @Robby-the-paladin собирается категорически отказываться от этой либы и писать что-то свое, поэтому парсинг может внезапно стать неактульным. Пока не знаю, как решать эту проблему

2024-02-21 12:34 UTC, TonitaN commented on libs/AutomataParser/src/Parser.cpp
> +	// https://lexy.foonathan.net/playground/
Сейчас как раз обсуждаем. Лексер, на мой взгляд, нормальный, там совсем немного переделать под атрибутность (просто не множить одинаковые почти лексические структуры, а переносить это в тип и потом генерировать такие структуры автоматически). Сами ведь знаете, что в парсере очень много одинакового для всех трёх структур. Так что много переделывать точно не придётся, но что-то придётся.

2024-02-21 13:12 UTC, TonitaN commented
Есть вопросы по совместимости. Библиотеку `unistd.h` подключила к Windows, не очень понимаю, зачем было привязываться к ней (магия с хешами не кажется столь обязательной). Но в вашей сборке у меня уже не генерируются шаблоны, не только для PDA, а вообще ни для чего. Проверьте кто-нибудь на винде, у вас та же история?

2024-02-21 13:15 UTC, alien-agent commented
> Есть вопросы по совместимости. Библиотеку `unistd.h` подключила к Windows, не очень понимаю, зачем было привязываться к ней (магия с хешами не кажется столь обязательной). Но в вашей сборке у меня уже не генерируются шаблоны, не только для PDA, а вообще ни для чего. Проверьте кто-нибудь на винде, у вас та же история?

Я честно говоря, вообще не знаю как она попала в код. Видимо IDE автоматически подключила. Сейчас удалю, вместе с исправлением всех замечаний.

2024-02-21 13:21 UTC, alien-agent commented on libs/Objects/src/PushdownAutomaton.cpp
> +std::vector<PDATransition> get_epsilon_transitions(const string& s,
Артефакт beta версии :)

2024-02-21 13:28 UTC, TonitaN commented
UPD: Что-то сломалось в логах ещё раньше: у меня всё работает на январской версии, но на нынешней размер логов при порождении шаблонов показывается равным 0.

2024-02-21 13:35 UTC, TonitaN commented
А в вашем случае есть проблема совместимости генерации lexy и windows - используется не тот слеш, из-за чего вылетает ошибка.

2024-02-21 13:35 UTC, alien-agent commented on libs/Objects/src/PushdownAutomaton.cpp
> +		if (state.identifier == "trap") {
Согласен, это было первое что пришло в голову, а потом забыл доработать. Ок ли в автомате хранить `optional` индекс ловушки и на него ориентироваться?

2024-02-21 13:38 UTC, xendalm commented on libs/Objects/src/PushdownAutomaton.cpp
> +		if (state.identifier == "trap") {
Вообще ловушка может быть и неявно задана, поэтому ее нужно искать по структуре автомата, наверное

2024-02-21 13:50 UTC, TonitaN commented
Удалила лишнюю библиотеку и запустила lexy совместимо. Ломается кодировка UTF-8 в логах вот тут:
```
```

2024-02-21 14:00 UTC, alien-agent commented
А можете проверить на master ветке? Такая строка помещается в отчет ровно в одном месте (Tester.cpp, строчка 97), и я к нему и близко не подходил (как и к refal-функциям которые это потом форматируют).

2024-02-21 14:06 UTC, TonitaN commented
Не все проблемные эпсилон-переходы обрабатываются корректно. При второй комплементации автомата Дика это видно.
[rendered_report.pdf](https://github.com/OnionGrief/Chipollino/files/14360458/rendered_report.pdf)

2024-02-21 14:06 UTC, TonitaN commented
В дополненном PDA есть переход между финальным и нефинальным состоянием, в котором просто обращаются финальности, без промежуточного состояния.

2024-02-21 15:07 UTC, TonitaN commented
> А можете проверить воспроизводится ли проблема на master ветке? Такая строка помещается в отчет ровно в одном месте (Tester.cpp, строчка 97), и я к нему и близко не подходил (как и к refal-функциям которые эту таблицу потом форматируют).

Вы правы - проблема образовалась раньше. Интересным образом, поскольку эти строчки и преобразование в text давно уже никто не трогал. Всё решилось заменой:
```
	t.columns.emplace_back("Шаги");
	t.columns.emplace_back("Длина строки");
	t.columns.emplace_back("Время разбора");
	t.columns.emplace_back("Результат разбора");

```
По смыслу так даже точнее, но конечно, нужно найти, почему `ь` вдруг расщепился посередине в текстовом режиме.

2024-02-21 16:37 UTC, alien-agent commented
@TonitaN Исправил ошибку. Почему-то я решил добавить в поиск "проблемных" переходов странное условие, которого не было в лекциях (на тот момент мне такой действие показалось логичным). И еще одно ненужная (даже вредная) проверка при простановке переходов из ловушки проблемных переходов.

2024-02-22 21:16 UTC, TonitaN commented
C отдельным эпсилон-переходом теперь работает. С эпсилон-замыканиями нет:
[rendered_report.pdf](https://github.com/OnionGrief/Chipollino/files/14379415/rendered_report.pdf)
И главное, я забыла в ТЗ для двоечников это написать, с них и не требовалось таких тонкостей)
Вам же желательно подредактировать критерий проблемности: если продолжение эпсилон-перехода по эпсилон-замыканиям может быть проблемным, то эпсилон-переход проблемный.

2024-02-24 10:27 UTC, alien-agent commented
@TonitaN Добавил учет эпсилон замыканий

2024-02-25 20:06 UTC, TonitaN commented
В равенстве неаккуратно проверяются символы перехода. См. тест, внимание на самый правый переход
[rendered_report.pdf](https://github.com/OnionGrief/Chipollino/files/14397682/rendered_report.pdf)
.

2024-03-06 02:12 UTC, alien-agent commented
> @alien-agent , нужно всё-таки внести фиксы по ревью @xendalm . Иначе в последующие годы без полного фикса курсовых никого не будем допускать к аттестации, и назовём это "Правило Пашкевича".

Не переживайте, исправлю на след неделе - жалко чтобы такой труд пропадал. (просто ушел в небольшой отпуск, поэтому чуть позже исправления будут)

2024-03-30 15:09 UTC, TonitaN commented
След недели давно стёрся, правило имени Пашкевича маячит на горизонте будущих четверокурсников...

2026-04-17 05:08 UTC, closed without merging