Преобразование автоматов pt. 2
StarikTenger/Chipollino pull request #33
Opened 2022-10-17 15:49 UTC by shevchenkokk

Добавлены функции:

- Минимизация ДКА

- Обращение НКА

- Добавление состояния-ловушки

- Удаление состояния-ловушки

Исправления:

- При нахождении пересечения, объединения и разности автоматов могло возникнуть множество состояний, недостижимых из начального. Такие состояния не нужны.

2022-10-19 13:49 UTC, StarikTenger requested changes

2022-10-19 13:49 UTC, StarikTenger commented on src/objects/FiniteAutomat.cpp
> +		 bool flag) {
### Проблема понятности кода
У функции очень нетривиальное поведение: она идёт по всем переходам, если флаг *True* и только по эпсилонам, если *False*. По-хорошему, это должно быть только по имени функции, но если уж не получается, то хотя бы по сигнатуре должно быть всё ясно. Ну и всегда можно написать поясняющий комментарий. 

Поэтому надо:
* Переименовать аргумент `vector<int> c` во что-то понятное (в *visited* мб)
* Переименовать `bool flag`, например, в `bool use_epsilons_only` (с таким названием его надо ещё и инвертировать)
* Добавить поясняющий комментарий

### Ссылки вместо указателей

Нет смысла передавать `vector<int>` указателем, лучше пользоваться ссылкой 
```c++
vector<int>& c
```

### set вместо vector
Возможно иммеет смысл вместо `vector<int> c` сделать `set<int> c`. В сете гораздо быстрее работает проверка на то, есть ли там элемент

Если важно знать, сколько раз каждый элемент входит, то тогда `map<int, int>`

2022-10-19 13:49 UTC, StarikTenger commented on src/objects/FiniteAutomat.cpp
> +vector<int> FiniteAutomat::closure(vector<int> x, bool flag) {
* надо назвать флаг понятным именем
* *x* тоже можно переименовать. В indices, например
* `vector<int>` можно передавать константной ссылкой, он внутри функции не изменяется

2022-10-20 00:13 UTC, xendalm reviewed
Пока объединение эквивалентных состояний работает правильно только для детерминированных

2022-10-20 17:21 UTC, StarikTenger approved these changes

2022-10-20 17:22 UTC, merged