Генератор входных данных
StarikTenger/Chipollino pull request #56
Opened 2022-10-26 02:48 UTC by mathhyyn

Интерпретатору и тайпчекеру посвящается

2022-10-26 16:58 UTC, StarikTenger requested changes

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/RegexGenerator.h
> +	RegexGenerator(int, int, int, int);
Если то, что обозначает аргумент не очевидно, то лучше всё-таки прописать названия аргументов в .h

Т.е. вот так:
```c++
RegexGenerator(int regex_length, int star_num, int star_nesting, int alphabet_size);
````

Ну и комменты перед публичными методами хорошо бы писать

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +};
лучше такие вспомогательные структуры внутри класса писать (кто-то другой, может быть, захочет у себя тоже такие названия использовать и будет конфликт имён)

так же имена типов предпочтительно писать с большой буквы

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +class TasksGenerator : BaseObject {
генератору не надо наследоваться от *BaseObject*

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +	string generate_declaration();
> Если то, что обозначает аргумент не очевидно, то лучше всё-таки прописать названия аргументов в .h

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +	int idNum = 0; // кол-во объявленных идентификаторов
* во-первых, *snake_case*
* во-вторых я бы назвал поля более понятными именами типа *max_functions_in_sequence* и *ids_declared*, но это уже придиирка

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +	function rand_pred();
Нужно ли что-то, кроме `generate_task`, выносить в *public*?

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/RegexGenerator.h
> +	vector<char> alphabet;
Вместо **char** при работе с алфавитом лучше использовать **AlphabetSymbol** (объявленный в *AlphabetSymbol.h*). Возможно, мы скоро сделаем символы алфавита строками, так что надо быть готовым

2022-10-26 16:58 UTC, StarikTenger commented on include/objects/TasksGenerator.h
> +// N3 = <object> <object>; N1 = Glushkov <object> <object>;
кстати, для напоминаний советую писать ключевое слово TODO, многие IDE умеют его подсвечивать. А ещё мы уже много где так пишем, так что удобно искать по всем TODO, куда нужно внести допилы

2022-10-27 03:07 UTC, mathhyyn commented on include/objects/TasksGenerator.h
> +	function rand_pred();
Вопрос хороший. Может кто-то, в теории, захочет создать операции отдельно. Но в таком случае набор объектов будет сохранен с предыдущего использования и обнулится при новом `generate_task`.

2022-10-28 19:16 UTC, StarikTenger requested changes
сделай явное задание сида в генераторе

2022-10-28 19:34 UTC, StarikTenger approved these changes
хорошо бы, конечно, запоминать куда-то сид, чтобы не потерять вариант генерации, но пока и так сгодится 👍

2022-10-28 19:35 UTC, merged