Regex to nfa
StarikTenger/Chipollino pull request #75
Opened 2022-10-29 12:06 UTC by dak151449

2022-10-29 12:47 UTC, StarikTenger requested changes
### АХТУНГ
оно не билдится, пофиксите
![изображение](https://user-images.githubusercontent.com/48261272/198832167-d0fbb8f7-5599-4d42-9d8b-ea7b28da2212.png)

2022-10-29 13:39 UTC, xendalm commented
![image](https://user-images.githubusercontent.com/35781938/198834675-c528ffcb-d7bf-41ef-8908-64a0154421ee.png)

2022-10-29 14:48 UTC, StarikTenger reviewed
В `to_glushkov` и `to_ilieyu` нужен закомментированный код или его можно удалить?

2022-10-30 10:03 UTC, StarikTenger approved these changes

2022-10-30 10:03 UTC, merged