Ambiguity
StarikTenger/Chipollino pull request #84
Opened 2022-10-30 19:20 UTC by xendalm

2022-10-30 20:15 UTC, StarikTenger requested changes
Если `enum AmbiguityValue` будет в **private**, то снаружи автомата с эти типом будет сложно работать. А нам, наверное, понадобится как-то сравнивать типы, чтобы их выводить

Так что лучше вынести в **public**

Поправьте меня, если неправильно понял задумку

2022-10-30 20:20 UTC, xendalm commented
Ну вывод я вроде как изнутри делаю, но если это может еще где-то пригодиться, могу вынести

2022-10-30 20:24 UTC, StarikTenger commented
Да, но при этом предполагается, что **Ambiguity** возвращает какое-то значение, с которым можно будет что-то делать
![изображение](https://user-images.githubusercontent.com/48261272/198900026-3940efb7-6fa4-411a-8e16-29523572c55a.png)

2022-11-01 22:48 UTC, StarikTenger approved these changes

2022-11-01 22:48 UTC, merged